INSERT INTO SELECT_REQUESTS(QUERY,RECEIVER,EVENT_TYPE,NOTIFICATION_LEVEL,QUERY_DESCRIPTION,MESSAGE,CONDITION)
VALUES ('SELECT * FROM Leaderboard', 'Participant', 'SCORE_CHANGES','ON_CHANGED_SCORE', 'Notify when any person gets at least 500 points.','You went up at least 500 points! CONGRATS!', 500);
INSERT INTO SELECT_REQUESTS(QUERY,RECEIVER,EVENT_TYPE,NOTIFICATION_LEVEL,QUERY_DESCRIPTION,MESSAGE,CONDITION)
VALUES ('SELECT * FROM Leaderboard', 'Participant', 'POSITION_CHANGES','ON_CHANGED_POSITION', 'Notify when any person climbs at least 1 position.','You went up at least 1 position! CONGRATS!', 1);
INSERT INTO SELECT_REQUESTS(QUERY,RECEIVER,EVENT_TYPE,NOTIFICATION_LEVEL,QUERY_DESCRIPTION,MESSAGE,CONDITION)
VALUES ('SELECT * FROM Leaderboard', 'Participant', 'POSITION_CHANGES','ON_CHANGED_POSITION', 'Notify when any person goes down at least 1 position.','You went down at least 1 position! Get back in there!', -1);
