INSERT INTO SELECT_REQUESTS(QUERY,NOTIFICATION_TYPE,MESSAGE,QUANTIFIER) VALUES ('SELECT * FROM Participants', 'POSITION_CHANGES','This is the whole leaderboard','All');
INSERT INTO SELECT_REQUESTS(QUERY,NOTIFICATION_TYPE,MESSAGE,QUANTIFIER) VALUES ('SELECT name FROM Participants WHERE points>=300', 'POINT_CHANGES','Here are people with 300 and above','Some');
