CREATE TABLE SELECT_REQUESTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QUERY varchar(255) NOT NULL,
    RECEIVER varchar(25),
    QUERY_DESCRIPTION varchar(255) NOT NULL,
    MESSAGE varchar(255) NOT NULL
);
